Add linux-cachyos & linuxPackages_hdr
chaotic-cx/nyx pull request #9
Opened 2023-04-08 08:16 UTC by dr460nf1r3

2023-04-10 13:54 UTC, PedroHLC requested changes

2023-04-10 13:54 UTC, PedroHLC commented on pkgs/linux-cachyos/config.nix
> +  CONTEXT_TRACKING = yes;
This is the upstream value.
```suggestion
```

2023-04-10 13:54 UTC, PedroHLC commented on pkgs/linux-cachyos/config.nix
> +  NO_HZ_IDLE = no;
The others are the upstream value.
```suggestion
  HZ_PERIODIC = no;
  NO_HZ_FULL_NODEF = option yes;
  NO_HZ_IDLE = no;
```

2023-04-10 13:54 UTC, PedroHLC commented on pkgs/linux-cachyos/config.nix
> +  HZ_500 = yes;
```suggestion
  HZ_500 = yes;
  HZ_1000 = no;
```

We have to remove the upstream value.

2023-04-10 13:54 UTC, PedroHLC commented on pkgs/linux-cachyos/config.nix
> +  LRU_GEN_STATS = no;
These are the upstream values.
```suggestion
  # LRU config
  LRU_GEN = yes;
  LRU_GEN_ENABLED = yes;
  LRU_GEN_STATS = no;
```

2023-04-10 13:54 UTC, PedroHLC commented on pkgs/linux-cachyos/config.nix
> +  USER_NS = yes;
This is the upstream value.
```suggestion
```

2023-04-10 13:54 UTC, PedroHLC commented on pkgs/linux-cachyos/config.nix
> +  ZSWAP_COMPRESSOR_DEFAULT_LZ4 = no;
```suggestion
  ZSWAP_COMPRESSOR_DEFAULT_LZO = no;
```
In NixOS, the default is LZO and not LZ4.

2023-04-10 13:54 UTC, PedroHLC commented on pkgs/linux-cachyos/config.nix
> +
```suggestion
```
No need for commented configs in-repo.

2023-04-10 13:54 UTC, PedroHLC commented on pkgs/linux-cachyos/config.nix
> +
```suggestion
```
Sorry, nixpkgs supports everything down to x86-64-v1

2023-04-10 13:54 UTC, PedroHLC commented on pkgs/linux-cachyos/config.nix
> +
```suggestion
```
This is the upstream value.

2023-04-10 13:54 UTC, PedroHLC commented on pkgs/linux-cachyos/config.nix
> +
```suggestion
```

This is the upstream value.

2023-04-10 13:54 UTC, PedroHLC commented on pkgs/linux-cachyos/config.nix
> +  UNINLINE_SPIN_UNLOCK = yes;
```suggestion
```

These are the upstream value.

2023-04-10 16:37 UTC, ptr1337 approved these changes
Seems good to me.

Hopefully ZFS support is now working proper.
Thanks!

2023-04-11 19:34 UTC, PedroHLC approved these changes
Probably needs some tweaking, but I tested it here with:
```nix
{
  # Creates a second boot entry for testing cachyos kernels
  specialisation.ptr1337.configuration = {
    system.nixos.tags = [ "ptr1337" ];
    boot.kernelPackages = lib.mkForce pkgs.linuxPackages_cachyos;
    boot.zfs.enableUnstable = true;
  };
}
```

and I can see that it worked:
```console
╭─pedrohlc at desktop in /home/pedrohlc
╰─λ uname -a
Linux desktop 6.2.10 #1-NixOS SMP PREEMPT_DYNAMIC Thu Apr  6 10:12:48 UTC 2023 x86_64 GNU/Linux
╭─pedrohlc at desktop in /home/pedrohlc
╰─λ zgrep 'BORE' /proc/config.gz
CONFIG_SCHED_BORE=y
```

[config.gz](https://github.com/chaotic-cx/nyx/files/11204284/config.gz)

2023-04-17 22:12 UTC, merged

2023-04-18 06:20 UTC, ptr1337 commented
IS the config now fixed? Does it work now correctly?

2023-04-18 08:00 UTC, dr460nf1r3 commented
It *should* - I've provided the config in the group for you to check a few days ago 👀