Fix overlay on NixOS 24.11
chaotic-cx/nyx pull request #945
Opened 2024-12-31 21:07 UTC by miketth

### :fish: What?

This PR fixes the overlay, so that binary caches work on NixOS 24.11.

### :fishing_pole_and_fish: Why?

It seems that using `pkgs.stdenv.hostPlatform` (if `pkgs` is from `nixos-24.11`) when importing `inputs.nixpkgs` (`nixpkgs-unstable`) causes the output hashes to diverge. This PR makes sure that we always use `stdenv.hostPlatform` from the Flake `nixpkgs` when using the Flake `nixpkgs` and not cross-compiling.

### :fish_cake: Pending

- [x] Complain with linter;
- [x] Remove some temporary fix;
- [ ] Publishing to news' channel.

### :whale: Extras

I tested this on my system and it fixed the output hashes mismatching and thus fixed the binary cache.

The "Why am I building a kernel?" section was really helpful while debugging this. Thanks!

2024-12-31 21:36 UTC, PedroHLC reviewed
The change is good, the reason is bad. I don't endorse mixing stable NixOS with our modules (that targets unstable).

2024-12-31 21:36 UTC, PedroHLC commented on modules/common/nyx-overlay.nix
> +            localSystem = flakes.nixpkgs.legacyPackages."${pkgs.system}".stdenv.hostPlatform;
I'm going to have to test this change a little because `pkgs.system` does not exist in every scenario.

2024-12-31 21:59 UTC, miketth commented
Ah, sorry if 24.11 (or any stable release) is unsupported. I can use the packages directly from `legacyPackages` too, so feel free to close if this is out of scope.

2025-01-07 14:14 UTC, PedroHLC requested changes

2025-01-07 14:14 UTC, PedroHLC commented on modules/common/nyx-overlay.nix
> +            localSystem = flakes.nixpkgs.legacyPackages."${pkgs.system}".stdenv.hostPlatform;
@miketth This is the original reference to a system's pkgs without `system`: https://github.com/chaotic-cx/nyx/pull/143#issuecomment-1576443907, later fixed in #144 + #151. I guess the solution here is to use `pkgs.stdenv.hostPlatform.system`.

2025-01-09 21:20 UTC, merged